# Server Configuration
server.port=8080
spring.application.name=master-chef-api

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://masterChefUser:Mateo0129*@masterchef.fepesil.mongodb.net/master-chef-recipes?retryWrites=true&w=majority&appName=MasterChef
spring.data.mongodb.auto-index-creation=true


# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method